### ISSUE TITLE
Errors encountered while running RD-Agent demo commands

### ISSUE THREAD

**Issue by Brayan233** [microsoft/RD-Agent#213]
Hi Team,

First off, I want to thank you for your hard work on RD-Agent. 

This project looks incredibly exciting, and I'm eager to explore its capabilities further. 

However, I ran into some issues while trying to run a few of the commands (demo app), and I wanted to share the details with you in case it helps improve the project.

### 1. Error with the command: **rdagent fin_factor**

Error message:

```
2024-08-18 23:39:17.858 | INFO     | rdagent.utils.env:prepare:172 - Building the image from dockerfile: /Users/xxx/miniconda3/envs/rdagent/lib/python3.10/site-packages/rdagent/scenarios/qlib/docker
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/envs/rdagent/bin/rdagent", line 8, in <module>
    sys.exit(app())
  ...
docker.errors.BuildError: The command '/bin/sh -c apt-get clean && apt-get update && apt-get install -y     curl     vim     git     build-essential     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

There’s a problem when building the Docker image, specifically during the apt-get installation process. The exit code 100 suggests a package installation or repository access failure.

### 2. Error with command: **rdagent fin_model**

Error message:

```
2024-08-18 23:55:20.099 | INFO     | rdagent.components.workflow.rd_loop:__init__:40 - Logging object in /Users/xxx/Documents/GitHub/RD-Agent/log/2024-08-18_21-55-16-538551/init/summarizer/15410/2024-08-18_21-55-20-094987.pkl
Workflow Progress:   0%|            | 0/5 [00:00<?, ?step/s]
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/envs/rdagent/bin/rdagent", line 8, in <module>
    sys.exit(app())
  ...
KeyError: 'Could not automatically map to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
```
This error appears to be related to the tiktoken module not being able to map the chat_model to a tokenizer. It looks like the model name might be missing or incorrectly specified.

### 3. Error with command: **rdagent fin_factor_report**

Error message:

```
2024-08-18 23:56:45.042 | INFO     | rdagent.utils.env:prepare:172 - Building the image from dockerfile: /Users/xxx/miniconda3/envs/rdagent/lib/python3.10/site-packages/rdagent/scenarios/qlib/docker
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/envs/rdagent/bin/rdagent", line 8, in <module>
    sys.exit(app())
  ...
docker.errors.BuildError: The command '/bin/sh -c apt-get clean && apt-get update && apt-get install -y     curl     vim     git     build-essential     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
This is similar to the first error, where the Docker build process fails due to an issue with the apt-get command.
```

### System Information
OS: MAC OS 15.0
Python Version: 3.10
RD-Agent Version: 0.1.0
Docker Version: 4.33.0

### .env Information
OPENAI_API_KEY=XXXXXX
CHAT_MODEL=gpt-4-turbo
CHAT_MAX_TOKENS=3000
CHAT_TEMPERATURE=0.7
EMBEDDING_MODEL=text-embedding-3-small

USE_AZURE=False
USE_AZURE_TOKEN_PROVIDER=False
MAX_RETRY=10
RETRY_WAIT_SECONDS=20

### Steps to reproduce

Run the following commands:

- rdagent fin_factor
- rdagent fin_model
- rdagent fin_factor_report

### Expected behavior

Each command should execute successfully without encountering Docker build issues or tokenizer mapping errors.

Thanks for the help!

**Comment by TPLin22** [comment]
Hello Brayan,

Thank you for bringing this issue to our attention. It appears that the problem might be due to compatibility issues with macOS, as our Docker environment and tests were primarily conducted on Linux.

As a temporary workaround, I would recommend trying to run rdagent in a Linux environment, where it was originally developed and tested. This might help circumvent the issue you're experiencing.

Meanwhile, we will look into enhancing macOS compatibility in future releases. Please let us know if running it on Linux works for you or if there are any other issues we can help with.
