### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by jobschang7** [microsoft/RD-Agent#228]
## To Reproduce

rdagent fin_factor

## Screenshot

![image](https://github.com/user-attachments/assets/f0abf665-adf7-481c-8c46-144843ecb604)

## Environment

 - RD-Agent version:main
 - Python version:3.10
 - OS: Linux

**Comment by you-n-g** [comment]
https://github.com/microsoft/RD-Agent/pull/234

Please  use the dev version before we release the new version. Thanks
