### ISSUE TITLE
No Scenario Info Detected

### ISSUE THREAD

**Issue by Leo-rq-yu** [microsoft/RD-Agent#263]
## ❓ Questions and Help

I followed the guide to run the User Interface in my local, but the app isn't running correctly. It didn't show any scenario descriptions. 
![rdagent_error](https://github.com/user-attachments/assets/65641123-c9e9-4a73-a91b-a798d8721d69)

**Comment by WinstonLiyt** [comment]
Hi Ruiqing,

To resolve the issue, please ensure you're specifying the correct path for the log files. This can be either **an absolute path or a relative path** (relative to where you're running `streamlit run rdagent/log/ui/app.py`). For example, you can use `log/2024-09-14_XX-XX-XX-XXXXXX` as a relative path if you're working within the `~/RD-Agent` directory.

Once the correct log path is provided, the app will automatically match it with the corresponding scenario and display the relevant content.

Please let us know if you need further assistance. Thanks!
