### ISSUE TITLE
Feature Request: Support for Open-Source LLMs in RD-Agent

### ISSUE THREAD

**Issue by NewWinHilton** [microsoft/RD-Agent#304]
## 🌟 Feature Description
Support for open-source llms (e.g., Ollama) in RD-Agent, allowing the integration and utilization of these models within the RD-Agent framework.

## Motivation

Adding Ollama, etc. will enable the exploration of new techniques without the limitations of proprietary APIs and costs. While current open source llms may or may not be viable today, they will improve over time and become versatile in the near future. The model ecosystem is rapidly evolving, with new models like Llama 3.1, Qwen, and many others emerging regularly, this will make it a perfect fit for this ecosystem.

**Comment by TPLin22** [comment]
Hi,
Thanks for your suggestion. We will consider incorporating it into our future plans. 
If you're interested in contributing to this feature, we would also be happy to provide guidance and feedback.
