### ISSUE TITLE
Is there a version of RD-Agent that does not need docker

### ISSUE THREAD

**Issue by lycanthropes** [microsoft/RD-Agent#312]
My operation system is ubuntu 22.10，and I find that docker does not support this version. So I have tried many times to deploy docker, but failed.  And I can go to next step for installing RD-Agent.

**Comment by TPLin22** [comment]
Hi,
Thanks for your feedback. The design of RD-Agent does indeed support running with a local environment, as configured in `rdagent/utils/env.py`.  However, this feature is not fully supported at the moment. We plan to enhance the code to support this functionality in the future. For now, we recommend using Docker to run the application.
