### ISSUE TITLE
Let's create a chat room for contributors

### ISSUE THREAD

**Issue by nicolasakf** [microsoft/RD-Agent#344]
Hi there,

I’d like to propose creating a dedicated chat space (I personally prefer Discord, but I’m open to alternatives) to streamline communication between contributors. As a newcomer to the project, I’m eager to start contributing, but I’m a bit unsure where to begin. I found my way here through the Qlib repository and would love to understand how these two projects are connected. I also have a lot of other questions that might be better addressed in a chat room rather than opening multiple issues and cluttering this repo.

Best regards

**Comment by wanghaoxue0** [comment]
Hey, great idea to have a chat room! This is no official chatting channel so far, However, welcome to join [LLMQuant Discord](https://discord.gg/nPZHP9c2d9) (many contributors of RD-Agent are there, LLMQuant is an open source AI community!). You can find both the discussion channels for RD-Agent and Qlib:)

**Comment by peteryang1** [comment]
Hello @nicolasakf. Thank you for feedback and your will to contribute to RD-Agent!

For an **official chatting room**, we are thrilled to announce our official Discord channel here: [https://aka.ms/RD-Agent-dc](https://aka.ms/RD-Agent-dc). Welcome to join this channel and we are happy to answer your questions in the chatbox!

For your question about the connection between QLib and RD-Agent. 
**So far** we use QLib as a real world simulator in RD-Agent loop to generate real-world backtesting metrics to the automated generated factors and models. 
**In near future** We are planning to make RD-Agent loop a configurable component in QLib to enable automated quant research on existing configurations.

**Comment by nicolasakf** [comment]
Hi @peteryang1 and @wanghaoxue0  thank you for your responses! Happy to join both servers. I'll close this issue and address further inquiries through there.
