### ISSUE TITLE
RD-Agent Discord chatting channel 

### ISSUE THREAD

**Issue by wanghaoxue0** [microsoft/RD-Agent#354]
For an official chatting room, we are thrilled to announce our official Discord channel here: https://aka.ms/RD-Agent-dc. Welcome to join this channel and we are happy to answer your questions in the chatbox!

For a more general exploration of AI with Finance/Quant. We set up [LLMQuant Discord](https://discord.gg/nPZHP9c2d9) (many contributors of RD-Agent are there, LLMQuant is an open source AI community!).

**Comment by Dalek626** [comment]
Hi, I want to join the discord group, but the link seems expired

**Comment by SunsetWolf** [comment]
Hi, @Dalek626 
Please enter from the badge on the homepage.
