### ISSUE TITLE
QR code of wechat group expired。

### ISSUE THREAD

**Issue by yexia553** [microsoft/RD-Agent#490]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [documentation](http://rdagent.readthedocs.io/). After that, if you still feel puzzled, please describe the question clearly under this issue.

Hi RD-Agent team, 

the [QR code](https://github.com/microsoft/RD-Agent/blob/main/docs/WeChat_QR_code.jpg) of wechat group expired, could you update it ?

**Comment by TPLin22** [comment]
Hi, 
Updated.

**Comment by yexia553** [comment]
> Hi, Updated.

thank you
