### ISSUE TITLE
llama is not installed

### ISSUE THREAD

**Issue by foureverlove** [microsoft/RD-Agent#507]
2024-12-19 17:38:30.048 | WARNING  | rdagent.oai.llm_utils:<module>:48 - llama is not installed.
I follow the document and it shows it is not installed? how to solve it?

**Comment by TPLin22** [comment]
Hi,
Thank you for your feedback. This warning message will not cause any errors because llama will only be activated when you set the `use_llama` environment variable.
Additionally, we have created a PR #509  to prevent the warning from appearing when llama is not in use.
